config/routes.rb
Rails.application.routes.draw do


  resources :accounts

  root to: 'visitors#index'
  devise_for :users,
             :controllers  => {
             :registrations => 'registrations'
            }
  resources :users
  resources :organisations, except: [:destroy]
  get 'organisations/order/:id', controller: 'organisations', action: 'order', as: 'order'
end

app/models/account.rb
class Account < ActiveRecord::Base

  after_create :insightly_create

  def insightly_create
    InsightlyWrapper.create_account(self)
  end

end

app/models/organisation.rb
class Organisation < ActiveRecord::Base
  belongs_to :user

  after_create :insightly_create
  def insightly_create
      Insightly2.client.insightly_create_organisation(self)
  end

  def insightly_update
    Insightly2.client.update_organisation(organisation: insightly_payload(true))
  rescue Insightly2::Errors::ResourceNotFoundError => e
    insightly_create
  end

  def insightly_update
    Insightly2.client.update_organisation(organisation: insightly_payload(true, true))
  rescue Insightly2::Errors::ResourceNotFoundError => e
    insightly_create
    Insightly2.client.update_organisation(organisation: insightly_payload(true, true))
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_create :insightly_create
  has_one :organisation
  def insightly_create
    Insightly2.client.insightly_create_contact(contact: self)
  end



end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      organisation_name = @account.organisation
      organisation_email = @account.email

      @account.assign_attributes( account_params )

      if @account.valid?
        # Insightly2.client.insightly_update_contact(contact: @account)
        # Insightly2.client.insightly_update_organisation(organisation: @account)
        InsightlyWrapper.update_account(@account)
        @account.save

        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:brick_mortar, :online, :phone, :name, :organisation, :email, :website, :address, :address2, :city, :state, :postcode, :country)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  before_action :set_organisation, only: [:show, :edit, :update, :order]
  before_action :authenticate_user!
  def index
  end

  def update
    respond_to do |format|
      if @organisation.update(organisation_params)
        @organisation.insightly_update
        format.html { redirect_to @organisation, notice: 'organisation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
      end
    end
  end

  def new
    @organisation = Organisation.new
  end

  def create
    @organisation = Organisation.new(organisation_params)

    respond_to do |format|
      if @organisation.save
        format.html { redirect_to @organisation, notice: 'Category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @organisation }
      else
        format.html { render action: 'new' }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
  end
    end
  end

  def show
  end

  def order
    @organisation.insightly_update
  end

  def edit
  end


  private


  def set_organisation
  @organisation = Organisation.find(params[:id])
end

  def organisation_params
    params.require(:organisation).permit(:name, :phone, :country, :address,
     :city, :state, :postcode, :user_id, :owner_id, :email, :website)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def new
    super
  end

  # POST /resource
   def create
     build_resource(sign_up_params)

     resource.save
     yield resource if block_given?
     if resource.persisted?
       if resource.active_for_authentication?
         set_flash_message :notice, :signed_up if is_flashing_format?
         sign_up(resource_name, resource)
         respond_with resource, location: after_sign_up_path_for(resource)
       else
         set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
         expire_data_after_sign_in!
         respond_with resource, location: after_inactive_sign_up_path_for(resource)
       end
     else
       clean_up_passwords resource
       set_minimum_password_length
       respond_with resource
     end
   end

   def update
# two wariants, first:
# super
# self.resource.insightly_update
#  fires always, even when user don't supply correct password during change
# second option shown below prevents that but extracting devise code from gem is not a good practice
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)

    resource_updated = update_resource(resource, account_update_params)
    yield resource if block_given?
    if resource_updated
      # user or order, other class will break devise
      self.resource.insightly_update
      if is_flashing_format?
        flash_key = update_needs_confirmation?(resource, prev_unconfirmed_email) ?
          :update_needs_confirmation : :updated
        set_flash_message :notice, flash_key
      end
      sign_in resource_name, resource, bypass: true
      respond_with resource, location: after_update_path_for(resource)
    else
      clean_up_passwords resource
      respond_with resource
    end
  end


  private

 def sign_up_params
   params.require(:user).permit(:first_name, :last_name, :email, :password,
   :password_confirmation, :phone, :country, :address, :city, :state, :postcode)
 end

 def account_update_params
   params.require(:user).permit(:first_name, :last_name, :email, :password,
   :password_confirmation, :current_password, :phone, :country, :address,
   :city, :state, :postcode)
 end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/organisations_helper.rb
module OrganisationsHelper
end

app/views/accounts/_form.html.haml
= simple_form_for(@account) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :phone
    = f.input :email
    = f.input :website
    = f.input :organisation
    = f.input :address
    = f.input :address2
    = f.input :city
    = f.input :state
    = f.input :postcode
    = f.input :country
    = f.input :brick_mortar
    = f.input :online

  .form-actions
    = f.button :submit

app/views/accounts/edit.html.haml
%h1 Editing account

= render 'form'

= link_to 'Show', @account
\|
= link_to 'Back', accounts_path

app/views/accounts/index.html.haml
%h1 Listing accounts

%table.table
  %thead
    %tr
      %th Phone
      %th Email
      %th Website
      %th Address
      %th Address2
      %th City
      %th State
      %th Postcode
      %th Country
      %th organisation
      %th Name
      %th Brick&Mortar
      %th Online
      %th
      %th
      %th

  %tbody
    - @accounts.each do |account|
      %tr
        %td= account.phone
        %td= account.email
        %td= account.website
        %td= account.address
        %td= account.address2
        %td= account.city
        %td= account.state
        %td= account.postcode
        %td= account.country
        %td= account.organisation
        %td= account.name
        %td= account.brick_mortar
        %td= account.online
        %td= link_to 'Show', account
        %td= link_to 'Edit', edit_account_path(account)
        %td= link_to 'Destroy', account, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Account', new_account_path

app/views/accounts/new.html.haml
%h1 New account

= render 'form'

= link_to 'Back', accounts_path

app/views/accounts/show.html.haml
%p#notice= notice

%p
  %b Phone:
  = @account.phone
  %p
    %b Name:
    = @account.name
%p
  %b Organisation:
  = @account.organisation
%p
  %b Email:
  = @account.email
%p
  %b Website:
  = @account.website
%p
  %b Address:
  = @account.address
%p
  %b Address2:
  = @account.address2
%p
  %b City:
  = @account.city
%p
  %b State:
  = @account.state
%p
  %b Postcode:
  = @account.postcode
%p
  %b Country:
  = @account.country
%p
  %b Organisation:
  = @account.organisation
%p
  %b Name:
  = @account.name

%p
  %b Bricks & mortar:
  = @account.brick_mortar

%p
  %b Online shop:
  = @account.online

= link_to 'Edit', edit_account_path(@account)
\|
= link_to 'Back', accounts_path

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <% if current_user.organisation.nil? %>
  <li><%= link_to 'Create organisation', new_organisation_path %></li>
  <% else %>
  <li><%= link_to 'Edit organisation', edit_organisation_path(current_user.organisation.id) %></li>
  <li><%= link_to 'Show organisation', organisation_path(current_user.organisation.id) %></li>
  <% end %>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
<li><%= link_to 'Create account', new_account_path %></li>
<li><%= link_to 'Show accounts', accounts_path %></li>
<% end %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Insightly2 Api'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Insightly2 Api'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/organisations/create.html.haml
%h1 Organisations#create
%p Find me in app/views/organisations/create.html.haml

app/views/organisations/edit.html.haml
= simple_form_for @organisation do |f|
  = f.input :name
  = f.input :phone
  = f.input :email
  = f.input :country
  = f.input :address
  = f.input :city
  = f.input :state
  = f.input :postcode
  = f.input :user_id, as: :hidden, input_html: { value: current_user.id.to_s}
  = f.input :owner_id, as: :hidden, input_html: { value: current_user.contact_id.to_s}
  = f.button :submit

app/views/organisations/index.html.haml
%h1 Organisations#index
%p Find me in app/views/organisations/index.html.haml

app/views/organisations/new.html.haml
= simple_form_for @organisation do |f|
  = f.input :name
  = f.input :phone
  = f.input :email
    = f.input :organisation
  = f.input :country
  = f.input :address
  = f.input :city
  = f.input :state
  = f.input :postcode
  = f.input :user_id, as: :hidden, input_html: { value: current_user.id.to_s}
  = f.input :owner_id, as: :hidden, input_html: { value: current_user.contact_id.to_s}
  = f.button :submit

app/views/organisations/order.html.haml
Insightly custom field updated

app/views/organisations/show.html.haml
%table.table.table-hover
  %thead
    %tr
      %th Name
      %th Phone
      %th Email
      %th Country
      %th Address
      %th City
      %th State
      %th Postcode
      %th Action
  %tbody
    %tr
      %td= @organisation.name
      %td= @organisation.phone
      %td= @organisation.email
      %td= @organisation.country
      %td= @organisation.address
      %td= @organisation.city
      %td= @organisation.state
      %td= @organisation.postcode
      %td= link_to "Order", order_path(id: @organisation.id)

app/views/organisations/update.html.haml
%h1 Organisations#update
%p Find me in app/views/organisations/update.html.haml

app/views/users/_user.html.erb
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>